### ISSUE TITLE
[BUG] The demo does not need to consider the background.

### ISSUE THREAD

**Issue by hhaAndroid** [IDEA-Research/OpenSeeD#11]
Panoptic segmentation and semantic segmentation are trained in sigmoid mode, so `demo_panoseg.py` and `demo_semseg.py` do not need to consider the background, otherwise it will report an index error.

**Comment by HaoZhang534** [comment]
Thank you for pointing our this. We will fix it soon.

**Comment by HaoZhang534** [comment]
This bug is solved.
