### ISSUE TITLE
The demo has relatively low performance.

### ISSUE THREAD

**Issue by hhaAndroid** [IDEA-Research/OpenSeeD#12]
I ran `demo_instseg.py` with your released weights and found that it did not detect any object, but if I used images and text descriptions that included people, then it worked normally. This indicates that the performance is relatively low for OV objects. I don't know why, have you run this script?

**Comment by HaoZhang534** [comment]
For our demo, you have to provide a set of categories. "Open-set" means that our model is able to deal with vocabulary different from the one our model is trained on. However, the aimed categories should be contained in the set of categories you set.

**Comment by hhaAndroid** [comment]
@HaoZhang534 I ran the script you provided directly without any modifications. You can try it yourself.

**Comment by choyingw** [comment]
I ran the demo script, and it worked fine in my case. I think if you test with a custom image, you should modify the class in either stuff and thing to include them in.

**Comment by HaoZhang534** [comment]
@hhaAndroid Hi, sorry for the late reply, as said by @choyingw, if you test with your only images, you sould change the class names to include the classes in your image.
