### ISSUE TITLE
Some questions of background queries

### ISSUE THREAD

**Issue by hhaAndroid** [IDEA-Research/OpenSeeD#14]
Dear author, after carefully reading through the code I have two queries that I hope you could answer at your convenience:

1. Conditioned Mask Decoding was not open sourced, is that correct?
2. I did not find the background queries part. I think what is currently open sourced is only an open vocabulary mask dino algorithm that can train on detection and segmentation datasets simultaneously, without specifically distinguishing foreground and background queries. I'm not sure if I understand correctly?

**Comment by HaoZhang534** [comment]
> Dear author, after carefully reading through the code I have two queries that I hope you could answer at your convenience:
> 
> 1. Conditioned Mask Decoding was not open sourced, is that correct?
> 2. I did not find the background queries part. I think what is currently open sourced is only an open vocabulary mask dino algorithm that can train on detection and segmentation datasets simultaneously, without specifically distinguishing foreground and background queries. I'm not sure if I understand correctly?

Yes, we are going to release the conditioned mask decoding and "decoupled queries" part in one or two days.

**Comment by HaoZhang534** [comment]
> Dear author, after carefully reading through the code I have two queries that I hope you could answer at your convenience:
> 
> 1. Conditioned Mask Decoding was not open sourced, is that correct?
> 2. I did not find the background queries part. I think what is currently open sourced is only an open vocabulary mask dino algorithm that can train on detection and segmentation datasets simultaneously, without specifically distinguishing foreground and background queries. I'm not sure if I understand correctly?

Hello, we have released the decouple code.

**Comment by hhaAndroid** [comment]
@HaoZhang534 OK. Let me confirm again.
