### ISSUE TITLE
How to do with this error?

### ISSUE THREAD

**Issue by Asasd23qw** [IDEA-Research/OpenSeeD#16]
RuntimeError: CUDA error: device-side assert triggered

**Comment by praeclarumjj3** [comment]
I was facing the same error, but then re-running progressed beyond this error and stops at another error (#18)

**Comment by stihuangyuan** [comment]
same error
<img width="595" alt="image" src="https://github.com/IDEA-Research/OpenSeeD/assets/18239907/24ddb83f-265b-4998-b24d-aeb812ee3351">

**Comment by yvfengZhong** [comment]
It's about the "background", see https://github.com/IDEA-Research/OpenSeeD/issues/11.

**Comment by HaoZhang534** [comment]
@Asasd23qw @praeclarumjj3 @stihuangyuan Sorry for the late reply, we have fixed the bug now.

**Comment by RYHSmmc** [comment]
？hello, do you fix this issue? I still get this issue when I run a demo...

**Comment by RYHSmmc** [comment]
@HaoZhang534
