### ISSUE TITLE
issues about your config

### ISSUE THREAD

**Issue by xiaomabufei** [IDEA-Research/OpenSeeD#17]
Hello thank you very much for your contribution but I don't really understand the config that you released！
for openseed_swint_lang.yaml, why the ADE20K train is contained?
![image](https://github.com/IDEA-Research/OpenSeeD/assets/104605826/eebcd839-52ce-4429-a5a6-b0ba1f980920)
for openseed_swint_lang_o365.yaml, why the object365 val is contained in the train?
![image](https://github.com/IDEA-Research/OpenSeeD/assets/104605826/699f4e77-2e35-4a08-b557-1dd0e71af3d5)
for openseed_swint_lang_o365_decouple.yaml, are there any misspellings?
![image](https://github.com/IDEA-Research/OpenSeeD/assets/104605826/c50b8cb6-1892-4cca-96da-f9b1ed0a7e48)
meanwhile, Is the latest version of the code currently available to reproduce the sota experiments in the paper?
Thanks again for your wonderful work, hopefully the experimental config file for swin-l can be released soon so that there can be more works based on this work.

**Comment by xiaomabufei** [comment]
@HaoZhang534  Looking forward to your reply！！

**Comment by yvfengZhong** [comment]
I have similar questions as well, particularly regarding the appearance of "object365_val_od" during training. For the "ade20k" dataset, I can provide an explanation. 

It appears that the datasets used for training depend on the "task_switch" and are not reliant on the "train_dataset_name". 

https://github.com/IDEA-Research/OpenSeeD/blob/23293ff1eff8de27ff3e13acaca75f613ce851f8/openseed/architectures/openseed_model.py#L276-L297

Additionally, it's important to note that the code only considers the scenario where the first dataset is "coco" and the second dataset is "object 365".

https://github.com/IDEA-Research/OpenSeeD/blob/23293ff1eff8de27ff3e13acaca75f613ce851f8/openseed/architectures/openseed_model.py#L120-L143

**Comment by HaoZhang534** [comment]
@xiaomabufei Hi, as @yvfengZhong commented, the ade20k is not used.

**Comment by HaoZhang534** [comment]
@yvfengZhong The training data should be "object365_train_od" instead of "object365_val_od". We have corrected it now. Yes, the current code only considers coco and o365 for training.
