### ISSUE TITLE
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by saltoricristiano** [IDEA-Research/OpenSeeD#23]
Hello, 

I don't know if I was the unlucky one but for running the code I needed to compile MultiScaleDeformableAttention CUDA Op.
In order to solve the issue:
```
cd openseed/body/encoder/ops
sh make.sh
```

Hoping this will help people having the same issue!
You could add it in the installation instructions just in case!
Best regards,
saltoricristiano

**Comment by achalddave** [comment]
Thanks for posting this, I would have been lost without this! If you're using a virtual env, you can instead do:

```
cd openseed/body/encoder/ops
python setup.py build install
```
