### ISSUE TITLE
train_net.py error

### ISSUE THREAD

**Issue by WanFeng123313** [IDEA-Research/OpenSeeD#25]
File "E:\docker\OpenSeeD\train_net.py", line 442, in main
    trainer._trainer.model.module = trainer._trainer.model.module.from_pretrained(cfg.MODEL.WEIGHTS)
  File "E:\ProgramData\Anaconda3\envs\torch113\lib\site-packages\torch\nn\modules\module.py", line 1265, in __getattr__
load original language language weight!!!!!!
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BaseModel' object has no attribute 'module'. Did you mean: 'modules'?

**Comment by 441599828** [comment]
@WanFeng123313 hi, I had the same error. What should I do?

**Comment by WanFeng123313** [comment]
> @WanFeng123313 hi, I had the same error. What should I do?

I just delete the module
"trainer._trainer.model.module.from_pretrained(cfg.MODEL.WEIGHTS)"
 -->" trainer._trainer.model.from_pretrained(cfg.MODEL.WEIGHTS) "

**Comment by HaoZhang534** [comment]
Hi @441599828 @WanFeng123313, I have fixed the error. The error occurs when you run with a single GPU.
