### ISSUE TITLE
1

### ISSUE THREAD

**Issue by 1012537710** [IDEA-Research/OpenSeeD#38]

**Comment by ZheyangH** [comment]
小黑子你现在能运行了吗sadsad

**Comment by 1012537710** [comment]
@ZheyangH 可以运行起来了。你需要准备一下自己的数据集目录
一、在官网下载这些数据，目录如下
coco/
  annotations/
    panoptic_{train,val}2017.json  # 全景分割train和val的标注文件，json格式的
  train2017 # 训练集原图
  val2017 # 验证集原图
  panoptic_{train,val}2017/  # png annotations  # 全景分割train和val的标注文件，png格式的
  panoptic_stuff_{train,val}2017/  # generated by the script mentioned below # 通过下面的代码运行得到的
二、获取panoptic_stuff_{train,val}2017

  Then, Install panopticapi by:
  pip install git+https://github.com/cocodataset/panopticapi.git
  run python datasets/prepare_panoptic_fpn.py, to extract semantic annotations from panoptic annotations.

具体的信息你可以去https://github.com/facebookresearch/detectron2/blob/main/datasets/README.md中找

**Comment by ZheyangH** [comment]
@1012537710 感谢感谢！
