### ISSUE TITLE
Number of qeuries for panoptic segmentation

### ISSUE THREAD

**Issue by strongwolf** [IDEA-Research/OpenSeeD#7]
According to the paper, there should be 400 (300 things and 100 stuff) queries for panoptic segmentation. However, I do not find this setting in the demo or evaluation codes. It seems that only 300 queries are used.

**Comment by FengLi-ust** [comment]
Yes, we have not released the code for using 400 queries. We will release it later.

**Comment by HaoZhang534** [comment]
We have released the decouple training code.
