### ISSUE TITLE
No Prediction on Custom Image

### ISSUE THREAD

**Issue by sindhuatquadrant** [IDEA-Research/OpenSeeD#9]
The model is not producing any output on custom images.
However, if I use the images provided in the repo, it works.

Any help would be appreciated.

**Comment by hhaAndroid** [comment]
https://github.com/IDEA-Research/OpenSeeD/issues/12

**Comment by HaoZhang534** [comment]
@sindhuatquadrant Sometimes, when your class name is too different from the training vocabulary, the prediction may not very good.
